"""Thin client for the Nexus Mods REST v1 API.

Reference: https://api-docs.nexusmods.com (Swagger: nexus-mods_public_api).
Every call needs a personal API key (Settings > API Keys on the Nexus Mods
website) sent as the ``apikey`` header.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Any

import requests

API_BASE = "https://api.nexusmods.com/v1"
USER_AGENT = "LMM/0.1 (Linux mod manager; +https://github.com)"


class NexusAPIError(RuntimeError):
    def __init__(self, message: str, status_code: int | None = None):
        super().__init__(message)
        self.status_code = status_code


class NexusRateLimitError(NexusAPIError):
    """Raised on HTTP 429. Nexus enforces hourly + daily quotas per key."""


@dataclass
class RateLimitStatus:
    hourly_limit: int | None = None
    hourly_remaining: int | None = None
    daily_limit: int | None = None
    daily_remaining: int | None = None


class NexusClient:
    """Stateless wrapper around the handful of v1 endpoints LMM needs."""

    def __init__(self, api_key: str, session: requests.Session | None = None):
        self.api_key = api_key
        self.session = session or requests.Session()
        self.last_rate_limit = RateLimitStatus()

    # -- low level -----------------------------------------------------

    def _headers(self) -> dict[str, str]:
        if not self.api_key:
            raise NexusAPIError("No Nexus Mods API key configured.")
        return {
            "apikey": self.api_key,
            "User-Agent": USER_AGENT,
            "Accept": "application/json",
        }

    def _get(self, path: str, params: dict[str, Any] | None = None) -> Any:
        url = f"{API_BASE}{path}"
        try:
            resp = self.session.get(url, headers=self._headers(), params=params, timeout=30)
        except requests.RequestException as exc:
            raise NexusAPIError(f"Network error contacting Nexus Mods: {exc}") from exc
        self._record_rate_limit(resp)
        if resp.status_code == 429:
            raise NexusRateLimitError("Nexus Mods API rate limit exceeded.", 429)
        if not resp.ok:
            raise NexusAPIError(
                f"Nexus Mods API error {resp.status_code} for {path}: {resp.text[:300]}",
                resp.status_code,
            )
        return resp.json()

    def _record_rate_limit(self, resp: requests.Response) -> None:
        h = resp.headers
        try:
            self.last_rate_limit = RateLimitStatus(
                hourly_limit=_int_or_none(h.get("X-RL-Hourly-Limit")),
                hourly_remaining=_int_or_none(h.get("X-RL-Hourly-Remaining")),
                daily_limit=_int_or_none(h.get("X-RL-Daily-Limit")),
                daily_remaining=_int_or_none(h.get("X-RL-Daily-Remaining")),
            )
        except ValueError:
            pass

    # -- endpoints -------------------------------------------------------

    def validate_user(self) -> dict[str, Any]:
        """Confirms the API key and returns account info (incl. is_premium)."""
        return self._get("/users/validate.json")

    def get_mod(self, game_domain: str, mod_id: int) -> dict[str, Any]:
        return self._get(f"/games/{game_domain}/mods/{mod_id}.json")

    def get_mod_files(self, game_domain: str, mod_id: int) -> dict[str, Any]:
        """Returns {"files": [...], "file_updates": [...]}."""
        return self._get(f"/games/{game_domain}/mods/{mod_id}/files.json")

    def get_download_links(
        self,
        game_domain: str,
        mod_id: int,
        file_id: int,
        nxm_key: str | None = None,
        nxm_expires: int | None = None,
    ) -> list[dict[str, Any]]:
        """Returns a list of {"URI", "name", "short_name"} CDN mirrors.

        Free-tier keys must supply the ``key``/``expires`` pair that comes
        from an nxm:// link generated by clicking "Mod Manager Download" on
        the website. Premium keys can omit both.
        """
        params: dict[str, Any] = {}
        if nxm_key and nxm_expires:
            params["key"] = nxm_key
            params["expires"] = nxm_expires
        return self._get(
            f"/games/{game_domain}/mods/{mod_id}/files/{file_id}/download_link.json",
            params=params,
        )

    def list_games(self) -> list[dict[str, Any]]:
        return self._get("/games.json")


def _int_or_none(value: str | None) -> int | None:
    return int(value) if value is not None else None
